name: Test if the script works
on: push

jobs:
  build:
    name: setup_and_run
    runs-on: ubuntu-latest
    steps:
      #- name: Maximize build space
      #  uses: easimon/maximize-build-space@master
      #  with:
      #    root-reserve-mb: 512
      #    swap-size-mb: 1024
      #    remove-dotnet: 'true'
      #    remove-android: 'true'
      #    remove-haskell: 'true'
      - name: prepare
        run: ./prepare.sh "$TARGETURL"
        env:
          TARGETURL: ${{ secrets.TARGETURL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      - name: download
        run: ./download.sh "$NEWFOLDERNAME" "$TARGETURL"
        env:
          TARGETURL: ${{ secrets.TARGETURL }}
          NEWFOLDERNAME: ${{ secrets.NEWFOLDERNAME }}
      - name: upload
        run: ./upload.sh "$NEWFOLDERNAME"
        env:
          NEWFOLDERNAME: ${{ secrets.NEWFOLDERNAME }}3
